### ISSUE TITLE
"Keep disconnected users" checkbox in Qt client

### ISSUE THREAD

**Issue by Oreonan** [BearWare/TeamTalk5#1033]
In online users dialog, add ability to keep disconnected users displayed. Feature migration from classic.

**Comment by bear101** [comment]
[Here](https://github.com/BearWare/TeamTalk5/blob/master/Client/qtTeamTalk/onlineusersmodel.cpp#L79) is where the user is normally removed. In your case you need to "transfer" the "keep disconnected" setting to the OnlineUsersModel (by creating a member variable).

Instead of removing the user in line 71 you should write:
m_users[userid].nUserID = 0
