### ISSUE TITLE
problem in windows 10 in team talk from 5.7 classic and versions after

### ISSUE THREAD

**Issue by alessio0292** [BearWare/TeamTalk5#1101]
dear All,
I report a problem that many people for example from Brazil reported in windows 10. The problem is this: when people or a person upload a file the person left automatically the server the problem there isn't first of 5.7. the person falls off the server.

**Comment by ChrisDuffley** [comment]
I've heard someone crash once but they were on Windows 11. Can't remember reproducing that issue.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

Sent from my iPhone 12 Pro Max

On Nov 2, 2021, at 08:34, alessio0292 ***@***.***> wrote:

﻿
dear All,
I report a problem that many people for example from Brazil reported in windows 10. The problem is this: when people or a person upload a file the person left automatically the server the problem there isn't first of 5.7. the person falls off the server.

**Comment by bear101** [comment]
Please provide a step-by-step guide on how to reproduce the issue. Then reopen it again.
