### ISSUE TITLE
Play continuously a sound when user is typing a private message

### ISSUE THREAD

**Issue by Nardol** [BearWare/TeamTalk5#1121]
When the person we privatly chat with is typing, there is an indication.
Could we also have an option to play a sound all the time the user is typing so playing it in loop?

**Comment by Nardol** [comment]
@CoBC do you think you could try to make something about his?

**Comment by amirmahdifard** [comment]
i even don't think this is a good idea y even you want to hear a sound when someone is typing? whats the point  of that?

**Comment by Nardol** [comment]
> i even don't think this is a good idea y even you want to hear a sound when someone is typing? whats the point of that?

Because you begin by saying you don't think it is a good idea and also because I don't think you are one of the people who could change the resolution of this issue, is it really useful to answer you?

I explained why I wish a sound to be played when the user is typing and it should only be when his/her conversation window would be focused.
Simply because there is a visual indicator and sound should be continued because we should know when user stopped writing.
And all sound events are possible to disable by setting no sound for it so in the case this suggestion could be implemented, user who don't need it could disable it.

Please don't begin by judging if you really want to know more.

**Comment by ChrisDuffley** [comment]
Preach it Patrick--I hear you! I would personally have it disabled but that's because I don't want sounds (I like rewinding back to speech events via speech history commands), but whoever wants it on can have it on. Dang, now if I had known C++ and the source code well enough, I'd send a PR with a suggesting implementation!

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On Aug 23, 2022, at 04:51, Patrick ZAJDA ***@***.***> wrote:


i even don't think this is a good idea y even you want to hear a sound when someone is typing? whats the point of that?

Because you begin by saying you don't think it is a good idea and also because I don't think you are one of the people who could change the resolution of this issue, is it really useful to answer you?

I explained why I wish a sound to be played when the user is typing and it should only be when his/her conversation window would be focused.
Simply because there is a visual indicator and sound should be continued because we should know when user stopped writing.
And all sound events are possible to disable by setting no sound for it so in the case this suggestion could be implemented, user who don't need it could disable it.

Please don't begin by judging if you really want to know more.

**Comment by Nardol** [comment]
> Preach it Patrick--I hear you! I would personally have it disabled but that's because I don't want sounds (I like rewinding back to speech events via speech history commands), but whoever wants it on can have it on. Dang, now if I had known C++ and the source code well enough, I'd send a PR with a suggesting implementation!

Maybe I exaggerated with the second point, I don't really think someone who could not fix the issue has nothing to say :wink: but telling the idea is bad before asking why it is proposed is not constructive and only a free judgement... Which is the cause of my previous reply :slightly_smiling_face:

Unfortunately except if I am wrong we have no real speech history on Linux and even if I had it, IMHO a continued sound would be more informative because with speech history we can know when the user started typing but unfortunately not if it is still the case because there is no speech event when user stopped typing.

**Comment by amirmahdifard** [comment]
i am just saying y do you care if someone is typing message or not?

**Comment by Nardol** [comment]
Because I don't want to begin writing while the person I am chatting to is writing, I prefer being sure all has been said before replying.
Messages which cross between them are not the best thing we can do except if we don't care about missing some messages :slightly_smiling_face: so the sound must be continuously while user is typing, having two separate sound one for "is writing" and another when user stopped could cause more confusions than a continuous sound as it was in JAWS with MSN Messenger for example, since the sound is played we know user is typing.

**Comment by artem59k** [comment]
Hello. This is really a very good idea. Also, if you don't need a sound that notifies you of a set of messages, you could turn it off in the settings. Then it is exactly clear: when a person types, or finishes typing. Of course, you can make an alert in TTS, but in the process of working on the device, you can skip the message that the username user has stopped typing. With a sound signal like in miranda, for example, it would definitely be clear when a person does not write a message.

**Comment by amirmahdifard** [comment]
@Nardol bro, i hope you read this and i hope that i get  an answer from you so i make sure that you've read it: i want to say, that i'm sorry and i'm sorry for what i said here, now, i really like this idea in qt teamtalk, because now i know how the system  of sound events works in qt teamtalk: before when i said that i don't like this idea, i was stil using classic and i didn't know that what is this at all: but now that i got to know Qt teamtalk more, this idea is actually grate for me because havving tts event and sound events for if user is typing a private message is grate! i hope they develop this one soon!

**Comment by CoBC** [comment]
I'll work on it for 5.17
One question here, as we only have indication for remote user typing every 5 seconds, should we choose a sound with a duration of 5 seconds, or just play a short osund every 5 seconds?
What do you think?

**Comment by Nardol** [comment]
IMHO five seconds looks a little long, for waiting as for playing, maybe a 2-3 second duration sound to have something between both solutions?
