### ISSUE TITLE
The menu to quickly change the output / input does not appear on Mac

### ISSUE THREAD

**Issue by math65** [BearWare/TeamTalk5#1208]
### Description

In Teamtalk 5.8.3, the menu does not appear.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

In the Client menu, the menu to change the output / input should appear.

### Actual behavior

It doesn't appear

### Steps to reproduce problem

* Open Teamtalk and go to the client menu

**Comment by ChrisDuffley** [comment]
Cannot reproduce; see the menu here in public release. Are you sure you are on 5.8.3 and not an unreleased build of it?

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On Jan 18, 2022, at 07:02, math65 ***@***.***> wrote:


Description

In Teamtalk 5.8.3, the menu does not appear.

Application

 qtTeamTalk
 TeamTalkAndroid
 iTeamTalk
 TeamTalkClassic
 TeamTalkServer
Platform

 Windows
 macOS
 Android
 iOS
 Linux
Expected behavior

In the Client menu, the menu to change the output / input should appear.

Actual behavior

It doesn't appear

Steps to reproduce problem

Open Teamtalk and go to the client menu

**Comment by math65** [comment]
Yes, I have the official version! :) but I have an M1 Mac

**Comment by bear101** [comment]
@CoBC Any idea why this is happening with French translation?

**Comment by bear101** [comment]
@CoBC It seems if the word "Configuration" appears in the menu item then it doesn't show up on macOS. If I change it to "Con Audio" then it shows up. Can we use some different translation?
