### ISSUE TITLE
Recording state should persist.

### ISSUE THREAD

**Issue by TheQuinbox** [BearWare/TeamTalk5#1257]
### Description

In TeamTalk classic, the recording state persisted across channel moves, server disconnects, client restarts, etc. In the latest QT client, this no longer happens; you have to start a recording every time.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [X] Linux

### Expected behavior

The recording behavior should work exactly how it did in TeamTalk Classic.

### Actual behavior

You have to start a new recording every time you move channel, disconnect/reconnect, etc.

### Steps to reproduce problem

1. Start recording
2. Relaunch the client

**Comment by ChrisDuffley** [comment]
For me at least on all my machines, this issue only occurred across TT restarts.

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

Sent from my iPhone 12 Pro Max

On Mar 5, 2022, at 16:55, Quin ***@***.***> wrote:

﻿
Description

In TeamTalk classic, the recording state persisted across channel moves, server disconnects, client restarts, etc. In the latest QT client, this no longer happens; you have to start a recording every time.

Application

 qtTeamTalk
 TeamTalkAndroid
 iTeamTalk
 TeamTalkClassic
 TeamTalkServer
Platform

 Windows
 macOS
 Android
 iOS
 Linux
Expected behavior

The recording behavior should work exactly how it did in TeamTalk Classic.

Actual behavior

You have to start a new recording every time you move channel, disconnect/reconnect, etc.

Steps to reproduce problem

Start recording
Relaunch the client

**Comment by bear101** [comment]
I also cannot reproduce the issue. It's correct that you have to activate recording again when you restart the client.

**Comment by TheQuinbox** [comment]
I just updated my TeamTalk to the latest beta, and it only happens now when you restart the client. I still don't like this though, as that's not what it did in TeamTalk Classic. Is there a particular reason this is the behavior?
