### ISSUE TITLE
It is not possible to move multiple users immediately in Qt client

### ISSUE THREAD

**Issue by kirill-jjj** [BearWare/TeamTalk5#1295]
### Description

Hello, in the classic TeamTalk I could click on Ctrl + Alt + x and move several users to another channel by clicking on Ctrl + Alt + V, but now, in Qt TeamTalk I can move only one user

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [ ] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Steps to reproduce problem

Try moving multiple users in Qt TeamTalk at once.

**Comment by ChrisDuffley** [comment]
Hello,

@bear101, I suggest you close this issue, as this can definitely be done, just in a different way. You do not use Ctrl+Alt+X to select a user for move. Instead, you would select people like you would do with multiple items in File Explorer, by shift+arrowing or Ctrl+arrowing/Ctrl+Spacing on people to move non-contiguously. You can then use the Ctrl+Alt+X keystroke to simulate the Cut to Clipboard action like you'd do in File Explorer. Afterwards, you can then do Ctrl+Alt+V to move those users to the new channel.

The only problem I have with this is for users who are trying to move non-contiguously on macOS, as I don't remember or believe it being as easy to do as it being done on Windows or possibly Linux. Continuous selection on at least Windows and macOS does work though, since you can see who you are moving with TTS.

Hope this helps!

Christopher Duffley
Host of Mission Possible Podcast: http://www.missionpossiblepodcast.com
Cell: +1 (603) 851-6971

Sent from my iPhone 12 Pro Max

On Apr 7, 2022, at 04:18, kirill-jjj ***@***.***> wrote:

﻿
Description

Hello, in the classic TeamTalk I could click on Ctrl + Alt + x and move several users to another channel by clicking on Ctrl + Alt + V, but now, in Qt TeamTalk I can move only one user

Application

 qtTeamTalk
 TeamTalkAndroid
 iTeamTalk
 TeamTalkClassic
 TeamTalkServer
Platform

 Windows
 macOS
 Android
 iOS
 Linux
Expected behavior

No response

Actual behavior

No response

Steps to reproduce problem

Try moving multiple users in Qt TeamTalk at once.

**Comment by kirill-jjj** [comment]
oh, sorry and thanks
