### ISSUE TITLE
Added a Menu that wasn't in TeamTalk5 QT, and added a feature that was in TeamTalk 5 Classic

### ISSUE THREAD

**Issue by dinifransiska** [BearWare/TeamTalk5#1339]
### Description

          1. Can see the Audio Codec when the channel is filled by several users, It should be in the View Channel Info section, this menu is allowed, this Audio Codec Info is also useful for users who don't randomly join channels, there are various reasons for that,
          A. Depletion of Internet Quota,
          B. Poor network.
          2. For screen reader users, Announcing transmission not showing,
          In the past, in TeamTalk 5 Classic, this menu was available, it would be nice if this menu was further improved in TeamTalk5 QT.
          3. The Playback mode menu that used to exist in TeamTalk 5 Classic to be added to TeamTalk5QT as well.
          4. Shortcuts to move users created 2 options, Menus that once existed in TeamTalk 5 Classic were also held in TeamTalk5 QT.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

I hope this can be considered before taking action to remove TeamTalk 5 Classic

### Steps to reproduce problem

Good morning TeamTalk QT users, and developers (bearware.dk).

Here I want to express my opinion, which this opinion can be considered by all developers.
And can be improved in the future.
Here I want to report what should be returned from what has been deleted.
After it was held in TeamTalk5 QT, I totally agree that TeamTalk 5 Classic should be removed.
Hopefully this can be a consideration for all developers.

**Comment by SalehAcehUtara** [comment]
Good morning to you too. I have no comments to make.

Let's just wait and be patient. as long as there is a better way why don't we use it first.
TeamTalk 5 Classic And TeamTalk5 Droid can still do that why don't we try to outsmart it using TeamTalk 5 Classic? Although, we are bothered, but it can't hurt right! 😠
Try to respect the developer.
If you find a lot of things that make you uncomfortable, try modifying them yourself. 😠
So that you know, how to build an Application from scratch to develop like this TeamTalk.

**Comment by dinifransiska** [comment]
Fuck you.

**Comment by dinifransiska** [comment]
You are very stupid, @SalehAcehUtara
