### ISSUE TITLE
Classroom updates announced to TTS

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#1401]
In Classic client the channel update event iterated the old user states and the new user states in class room channels and made a TTS update:
https://github.com/BearWare/TeamTalk5/blob/master/Client/TeamTalkClassic/TeamTalkDlg.cpp#L1763

### Discussed in https://github.com/BearWare/TeamTalk5/discussions/1399

<div type='discussions-op-text'>

<sup>Originally posted by **computertech1012** July 17, 2022</sup>
Hi,
In TeamTalk 5 Classic, all classroom announcements are reported, for example, when everyone can or can't transmit voice. I am wondering if this feature can be added as well to the QT client?
Does anyone else think this would be a good idea? Because at the moment QT TeamTalk only reports when you can  and can't transmit voice. But it should report for all classroom changes.
It's also good, so that if you take away someone's voice or video then you will know that it's been removed via a TTS event.
Thanks for reading.</div>

**Comment by ChrisDuffley** [comment]
I agree with this proposal. I wish I had this little earlier, because one time when I needed to help moderate a Classroom mode channel, I had to manually go to the Transmit Control under Users and make sure people's voices were on after turning it off. Took quite a while to do because of no updates other than my own audio.
