### ISSUE TITLE
New instance using new profile use current profile

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1479]
### Description

When you use the "New Client instance" menu-item, and select "New profile" in combobox, a dialog to enter a profile name appears, but when you click on "OK" button, a new client instance start using your current profile. More, the TeamTalk5.ini.x file contains all your settings.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [X] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

New profile should create an empty profile from scratch

### Actual behavior

Your current settings are applied in new profile

### Steps to reproduce problem

* Create a new client instance
* Choose "New profile" and type a name
* Click on "OK" button

**Comment by bear101** [comment]
This current behaviour, with copying the current ini-file, has always been the case, so it's not a bug but a feature. But we can change it so new ini-file will be used. I guess we just have to delete [this line](https://github.com/BearWare/TeamTalk5/blob/master/Client/qtTeamTalk/mainwindow.cpp#L3928).

**Comment by CoBC** [comment]
Yes, I suggest to change it because we already have "Current profile" to 
use same settings in new instance. Alternatively add a checkbox to 
choose if new profile should include current settings or not.

**Comment by ChrisDuffley** [comment]
Can we see if the checkbox for using existing settings could be implemented as @CoBC had thought about/mentioned? Reason is because I use the main instance for my main setup and streaming for if I want to stream something through Virtual Audio Cable or another part of a sound card. Only problem: Every time I add a new server or modify one, I need to delete and recreate it so that I can have an updated copy of my server list and then can reset preferences again. I don't want these other preferences I may set in the streaming instance (in this current case) to stick with my main instance. The old behavior was actually good for what I needed it to do, hence me asking for this. While a fresh INI may be nice, I don't see it as a good thing if I have over 30 to 40 servers in my list I may hop on from time to time, including my own one, thatI'd have to re-add all the time.

Alternatively, is it possible if the server list entries can be mirrored across profiles? It then wouldn't matter whether a fresh preferences section of the INI would be used in that case.

Thank you!
