### ISSUE TITLE
Transmission controls in channels tree doesn't work as expected

### ISSUE THREAD

**Issue by CoBC** [BearWare/TeamTalk5#1663]
### Description

When using transmission controls (columns) in channels tree to control stream of an user, when you try o uncheck the last column, all other streams are re-enabled. Problem isn't present when using shortcut or menu item to do the same operation.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

Controls should work normally.

### Actual behavior

All stream type are restored when toggle last control.

### Steps to reproduce problem

* Uncheck 4 of 5 stream type on an user
* Uncheck the only column still checked: all stream type are re-enabled and last isn't disabled.

**Comment by amirmahdifard** [comment]
i stil have a question that wy we should have those in channels tree? we have shortcuts and context menu to toggle those and it's good enough: onnistly those transmitions in the channel tree just make me confuse when i'm opening a channel submenu: i even said, add an option to display tab in settings, something like show transmition controles in channel tree chek box, but you didn't lissen so.

**Comment by computertech1012** [comment]
Hi,
I also noticed a bug with transmission control as well.
If you are outside of a channel, and you are an admin, if you do CTRL+ALT+Q on a person it will take away all of their transmission rights instead of just voice. This happens also when in classrooms. It doesn't effect tree view but does effect when you use the shortcuts.
Also, when you use the shortcuts if let's say you have a classroom channel with only voice enabled and text messaging enabled, if you use the shortcut to disable voice it disables all of it even if the admin is not in the room.
And finally, if you have a classroom channel, in the tree view, and you leave it and go to another channel, if you go back to that classroom channel without joining it, you will discover that if you go on the tree view, the desktop transmission allowed will be able to be checked and unchecked and this I think is a bug. Because of course if you uncheck it it removes everything. And this only effects admins.
Personally, I think that admins should be able to control channels even if not in the channel, and should be able to control everything.
Thanks for reading!

**Comment by computertech1012** [comment]
Hi,
I need to make a correction. This would also happen if you are an operator of the channel, and also note that this does not happen if the admin is actually in the channel, only when not in the channel of which he's trying to control.
If you are operator of the channel you leave the channel and you still have this bug, though not with the desktop check box. 
I hope I am explaining it correctly.
Thanks for reading!
