### ISSUE TITLE
Mute button isn't working (media/voice)

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#173]
User properties view controller

**Comment by amaldonado4** [comment]
Hello. Let me first off congratulate you Bearware.dk for an excellent iOS iTeam Talk app. It is very user-friendly for someone who is visually impaired. With this in mind, i would like to present to you a few issues that I have found that is a concern as both a user, as well as admin of a server. First, I would like to see iTeam Talk have its mute button fixed. when I join a channel I'm automatically transmitting. I feel this is a concern especially if a meeting is taking place in a room and the iOS user is unable to mute his/herself. Secondly, I would like to somehow suggest that when a call is coming in on an iPhone, team talk gets muted and upon the call terminating, Team Talk can resume joining the room. Often times, I've seen users having to sign out of the app and reconnect when this happens. From an admin side, I would like to have the ability to somehow move users at once instead of not having this ability at all. I often times can be away from the computer and still participate and if I'm the only admin and I need to move users into a different room, I would like to be able to assist. I know I may have more, but these are my concerns for now. I appreciate the work you are putting into the iOS app and thank you for your hard work.

**Comment by bear101** [comment]
Hi, if you filter using the iTeamTalk label then you'll see all the existing issues. I believe the issues/features you mention are already listed.
