### ISSUE TITLE
Remove public servers from server list

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#1872]
### Discussed in https://github.com/BearWare/TeamTalk5/discussions/1849

<div type='discussions-op-text'>

<sup>Originally posted by **lucaschambers** April 25, 2023</sup>
Hello there! I wanted to bring to your attention that the public servers in the team talk application are becoming less reliable since the addition of unofficial servers. As a solution, I propose that you remove the entire public server feature and give users the ability to select their preferred language or country in order to find servers within their desired communities. This way, users can find as many servers as they want, similar to other conferencing applications.
Also, the developer doesn't need to bother themselves with adding or removing servers from the public servers all the time. This is because anyone can add their servers to the unofficial section, and people can find their community easier this way.
Thank you for considering this suggestion, and please let me know if you have any questions or comments.</div>

**Comment by amirmahdifard** [comment]
also, add an ability for users to be able to delete their unoffitial servers that they have added before, raather than just deleting that account from the server

**Comment by amirmahdifard** [comment]
what about classic client that does not support unoffictial servers?

**Comment by bear101** [comment]
it will only support official servers.

**Comment by amirmahdifard** [comment]
so the check box for inclooding public servers will be removed from classic? the classic client is marked for deletion anyway so, good luck. you can even no longer update the classic client vertion.

**Comment by Muamalaljanahi** [comment]
bad idea for several reasons:
1. There are many unofficial servers owned by untrustworthy individuals, which can damage the reputation of the software itself.
2. There are many abandoned servers, which can cause disruption to users, especially those using the phone, as there is no feature to sort servers based on members or country.
3. The abundance of unofficial servers without sorting them according to the real country of the server members, rather than the country where the server is located, leads to user confusion and their inability to identify a server specific to their language/culture.

In addition to the above reasons, I don't see any logical reason that requires deleting public servers.

**Comment by lbk2907** [comment]
> 2. There are many abandoned servers, which can cause disruption to users, especially those using the phone, as there is no feature to sort servers based on members or country.
@Muamalaljanahi this can be added later on

**Comment by lbk2907** [comment]
> 2. There are many abandoned servers, which can cause disruption to users, especially those using the phone, as there is no feature to sort servers based on members or country.

@Muamalaljanahi this can be added later on

**Comment by lbk2907** [comment]
> also, add an ability for users to be able to delete their unoffitial servers that they have added before, raather than just deleting that account from the server

@amirmahdifard you can use #teamtalkdelete# to delete it from the unofficial server list without need to delete the account from your server

**Comment by kirill-jjj** [comment]
I think that users themselves should determine the country of their unofficial server. As I said, I have several servers, one of them is in Germany, but this server hosts a teamtalk server for Ukrainians.

**Comment by lucaschambers** [comment]
Hello there! I think removing public servers is a good idea because it can be difficult for the developer to constantly update them and keep them active, which takes a lot of time and effort. Many public servers have already been taken down since this announcement. As I mentioned before, it would be great if there was an option for users to select their country and see all the unofficial servers located there. Public servers are exclusive to a specific community, which can prevent others in the same country from communicating with each other. Other applications allow users from one country to host as many servers as they want, and if the server owner is from a different country, they should name their server accordingly and specify its location. Thank you for taking the time to read this!

**Comment by bear101** [comment]
The country column is shown to give a geographical location of the server, so you can look for a server with low latency.

**Comment by lucaschambers** [comment]
that's a good idea.

**Comment by lucaschambers** [comment]
In my opinion, public servers should have been removed earlier since they can cause a lot of confusion for users. After removing all public servers, it would be great if unofficial servers were turned on by default.

**Comment by amirmahdifard** [comment]
yes, i very agree public servers should be removed a s a p

**Comment by lucaschambers** [comment]
hello there, I noticed the release of Team Talk v5.14 and it seems that public servers are yet to be removed. Thus, I'm leaving a comment to inquire about the status of the situation. Please update us here if there's any news about it. Thank you.

**Comment by bear101** [comment]
@lucaschambers check the status of the issue.

**Comment by lucaschambers** [comment]
If I understand correctly, is the process of removing the public server feature still ongoing?

**Comment by bear101** [comment]
Yes, it's not closed https://github.com/BearWare/TeamTalk5/milestone/68

**Comment by lucaschambers** [comment]
Ah, I completely comprehend.
