### ISSUE TITLE
TeamTalk Crashes when unbanning multiple users at once

### ISSUE THREAD

**Issue by Ramon-Salazar** [BearWare/TeamTalk5#2136]
### Description

this bug exists long time ago, since v5.7 or probably lower that teamtalk crashes when unbanning multiple users.

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

When selecting multiple users in the ban users dialog and when clicking remove ban user, it should remove all of them.

### Actual behavior

When unbanning the selection of multiple users it crashes

### Steps to reproduce problem

1. by going to the ban users list.
2. select multiple users, at least 5 or more.
3. then remove the ban.
4. Hit OK.

**Comment by bear101** [comment]
@CoBC I wonder if this is due to the screen-reader. When I have Windows Narrator enabled then the "Banned Users" dialog  become unresponsive when there's many items. Try listing banned users on the public servers and navigate in the list view with banned users.

Without Windows Narrator enabled then there's no issue. Also on macOS using VoiceOver I don't have any issue.

**Comment by CoBC** [comment]
It's an issue with some screen-readers when a lot of UIA events are 
send, For NVDA this will be fix in next release, don't know for other 
screen-readers
