### ISSUE TITLE
qtTeamTalk:TeamTalk v. 5.18.0.5150: After switching to Qt Accessibility Notifications in /Preferences/Text-to-Speech, it's impossible to switch back to Tolk.

### ISSUE THREAD

**Issue by dpy013** [BearWare/TeamTalk5#2494]
### Description

Environment: Windows 24H2 (OS Build 26100.2454)

### Application

- [X] qtTeamTalk
- [ ] TeamTalkAndroid
- [ ] iTeamTalk
- [ ] TeamTalkClassic
- [ ] TeamTalkServer

### Platform

- [X] Windows
- [ ] macOS
- [ ] Android
- [ ] iOS
- [ ] Linux

### Expected behavior

Switching to Qt Accessibility Notifications allows switching back to Tolk without issue.

### Actual behavior

TeamTalk v. 5.18.0.5150 crashes after switching from Tolk to Qt Accessibility Notifications and then back to Tolk.

### Steps to reproduce problem

1. Run TeamTalk v. 5.18.0.5150.
2. Press F4 to open Preferences and select the Text-to-Speech tab.
3. Change the Text-to-Speech engine combo box to "Qt Accessibility Notifications" and confirm, restarting the software.
4. After restarting, repeat steps 2 and 3, but this time change the Text-to-Speech engine combo box from "Qt Accessibility Notifications" back to "Tolk".  This will reproduce the error.

**Comment by dpy013** [comment]
cc @CoBC

**Comment by CoBC** [comment]
I can't reproduce on my side :(

**Comment by dpy013** [comment]
Can TeamTalk access/view debugging logs? I can provide the specific error logs.

**Comment by amirmahdifard** [comment]
for me also works fine, please delete all your teamtalk data and start fresh and let teamtalk do the new configs, your problem will be solved

**Comment by dpy013** [comment]
The issue was resolved by reinstalling the application over the existing installation.

**Comment by amirmahdifard** [comment]
@dpy013 i'm glad your problem has been resolved. sometimes old config files cause problems for the updated application because the config file may contane a specific data that method of supporting that data in the application has been changed, but your data is stil old, which will lead to a crash, unexpected bug, sound not playing, etc. so, from now on whenever you've faced a problem, first, start everything fresh and delete old data, and if your problem stil continued, report it. good luck!
