### ISSUE TITLE
iTeamTalk cannot connect on T-mobile network in US

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#311]

**Comment by Nick6489** [comment]
@bear101 A few friends of mine, and I, tested this quite extensively. What we figured out is that T-Mobile uses some apparatus of its own to translate IPV4 addresses into IPV6. When connecting to a TeamTalk server hosted on an actual IPV6 network, TeamTalk exhibits the same behavior. It is our understanding from this test that TeamTalk does not yet support IPV6 on the iPhone?

**Comment by bear101** [comment]
No. It does not have IPv4/6 translation. But then how come Android works on T-Mobile?

**Comment by bear101** [comment]
There's a new iOS client on TestFlight now which supports IPv6. Can you 
check it out?

--
Kind regards

Bjoern D. Rasmussen
www.bearware.dk

**Comment by OzancanKaratas** [comment]
@bear101 Do not get mad at me but Apple is behaviours bad to me. My Apple ID was changed. Please new invitation to ozancankaratas96@outlook.com. Thanks. I will delete this comment if invitation mail comes.

**Comment by tech10** [comment]
A friend of mine tested the test flight version of the client. The same result has occurred, no connection unless he's connecting through some VPN service like Private Internet Access. WIFI, of course, works fine. While having an IPV6 capable iOS or mobile client in general would be a good thing, it doesn't solve the issue. Other programs don't work correctly on T-Mobile, either, nor do non-standard ports for icecast or other audio/video streams. In my opinion, T-Mobile is blocking ports that are unused by the majority, in which case, no code within the application itself is likely to solve the problem. It would be on T-Mobile's side of things to correct, which they did for a few days until a carrier settings update, then returned to the prior behavior. This is what gives me the suspicion that T-Mobile is blocking ports, rather than it being an application issue.

**Comment by OzancanKaratas** [comment]
A user had written to website. Users must get operator updates provided by T-Mobile to connect. [https://support.apple.com/en-us/HT201270](Refer this link to get updates from your iOS device)

**Comment by OzancanKaratas** [comment]
Use unlimited network access for the iOS app.

**Comment by stickbear2015** [comment]
I forgot this issue existed, latest build, still refuses to work.

**Comment by tech10** [comment]
I suspected that it wouldn't work myself, and a friend of mine, who uses T-Mobile, confirmed that enabling IPV6 didn't resolve the issue. While that's a good thing to have enabled anyway, I suspect that the issue is not within the application, but T-Mobile, who block the majority of non-standard ports, something most people probably wouldn't notice. The same friend told me he couldn't connect to internet streams on port 9000, while 8000 works. This, combine with TeamTalk being unable to connect unless using a VPN, leads me to my suspicions. Whatever the T-Mobile folks or testing says about requiring IPV6 in an application in order for it to properly work, is incorrect.

**Comment by Nick6489** [comment]
This has changed significantly.

IPV4 TeamTalk servers are still unable to connect using iTeamTalk, owing to what appears to be some kind of tunnel that T-Mobile is using to handle IPV4 traffic. Not something we can really do anything about.

However, IPV6 TeamTalk servers *do* work now. Tested on two T-Mobile iPhones using both the store build and the latest beta yesterday. This is why @Quinnebert was asking for a build that would disable IPV6_V6ONLY in sockopts in [this forum post](http://www.bearware.dk/phorum/read.php?1,4940)

**Comment by bear101** [comment]
Are you able to connect to the IPv6 TeamTalk servers in the public server list?

**Comment by bear101** [comment]
@stickbear2015 @tech10 @Nick6489

**Comment by Nick6489** [comment]
Yes, I can connect to both US and UK IPV6 public TeamTalk servers from my T-Mobile iPhone 6S.

**Comment by Nick6489** [comment]
What I'm about to say doesn't change that I would like one TeamTalk server instance to bind to IPV4 and IPV6 on the same machine in future versions...But your latest beta on the app store suddenly allows me to connect to IPV4 TeamTalk servers through T-Mobile, despite their rather aggressive, ludacris IPV6 tunnel.

**Comment by bear101** [comment]
The v5.3.2.4928 betas you find here can bind to multiple IP-address:
http://bearware.dk/beta/
