### ISSUE TITLE
problems adjusting speaker volume, microphone gain and voice activation level on android 8, both tablet and phone

### ISSUE THREAD

**Issue by okevinalmeida** [BearWare/TeamTalk5#390]
What the tittle says: Double tapping on the buttons doesn't do anything.

**Comment by poretsky** [comment]
In fact, it is the old problem that affects TX button as well. I've
solved it now. See my commit 46c499bad02c9361c5309ee407cfd6735ebed8e1 in
master branch.

I think, it would be reasonable to make a bugfix release for Android,
since actually the problem is really annoying for all users concerned
with accessibility service.

**Comment by abdullah5490** [comment]
Hello there, I'm still facing the same issue on android9 with teamTalk 5.3.4 installed yesterday. Is it not resolved permanently? @poretsky
