### ISSUE TITLE
Teamtalk 5.4 classsic fails to stream media file 

### ISSUE THREAD

**Issue by burakyuksek** [BearWare/TeamTalk5#439]
Hello,
I used to be able to stream the files I tried, but now I can't stream any file. I tried uninstalling and reinstalling but it didn't help. What can I do to fix this?

**Comment by OzancanKaratas** [comment]
Hello Burak,

I'm using TeamTalk 5.4, but I don't have such problem.

Consult your TeamTalk server administrator or if you are an administrator, allow media streams in the server.

1. Press F9 in your server.
2. Set as 0 the value “Media File TX max”.

**Comment by bear101** [comment]
Are you using Windows 7?

**Comment by burakyuksek** [comment]
Hello,
Yes, windows7 64-bit.

Bjørn Damstedt Rasmussen <notifications@github.com> şunları yazdı (12 Tem 2019 19:26):

> Are you using Windows 7?
>

**Comment by bear101** [comment]
TeamTalk v5.4 has been optimized for Windows 10. This unfortunately
means that compatibility with Windows 7 is not as good as before.
Microsoft is stopping support for Windows 7 in 6 months and there is not
much point in supporting an unsupported OS in future versions of TeamTalk.

Windows XP support also had to be dropped in TeamTalk v5.3 because the
OS is simply out of date.

--
Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk
