### ISSUE TITLE
A password for leaving channels

### ISSUE THREAD

**Issue by Ramon-Salazar** [BearWare/TeamTalk5#445]
hi @bear101 
It'll be nice if this feature will be available, for example when creating channels to prevent people from leaving like prison, Jail and so on

**Comment by ntcarver0** [comment]
This could be abused by spammers and other nefarious individuals, and can be easily circumvented by disconnecting from the server and reconnecting, depending on the server's configuration.

**Comment by Ramon-Salazar** [comment]
You're almost right, but ujusting login delay can make it too hard for people to disconnect and connect, so I think this feature is so good, cause I myself don't like kicking and banning too much, and this way could be a democrasy if we Moved People to the specified channel like Jail, Prison or slammer instead of kicking them, banning them from Channel or from the server

**Comment by tech10** [comment]
I see little reason for such a feature. After all, a person can simply disconnect to leave the specified channel, even if they may not be able to log in right away again. It's easily circumvented, and if someone is doing something wrong, then they simply ought to be kicked or ban from the channel or server in question.

If it was taken one step further and the client prevented from disconnecting, that would then introduce an undesired element of administrators having far too much control over a clients abilities than they should. Even this feature of a password for leaving a channel, in my opinion, would give a bit more control than is reasonable. If someone wants to leave a channel, they should have the ability to do so without requiring a password. If someone is doing something wrong, then as I stated above, kicking and banning are the best options in my opinion.

**Comment by Ramon-Salazar** [comment]
@tech10 But there is a possibility to set an initial channel for a user so even reconnecting won't help, so still the feture is usefull and as I said I don't like kicking and banning that much so this feature is a perfect option

**Comment by tech10** [comment]
To me, that's taking away a person's right to freedom if they connect to the server. Basically, you'd be telling them that they can connect, but they can only go to this specific channel, and they can't leave that specific channel unless they disconnect from the server all together, or the account is changed to prevent them from joining such a channel. If someone is ban from a server or their account removed, then they simply won't be able to connect to that server in the first place, due to the ban. Even though they can't connect, the user still has more freedom. When you enforce them that, upon connecting to a server they're made to join a channel they can't leave, you're taking away their free choice of what they can do while connected to the server. In some ways, it's as good as a ban, so why not simply ban them in the first place? Also, anyone else joining that channel who then wants to leave, would require the password to leave. What if they weren't part of this punishment principle? Do they deserve to be trapped in the channel without the password to leave it? Then, if they obtain that password, they could simply transmit it to all the others there, which would then circumvent the entire idea of this prison.

Also, consider that you can remove a person's rights to transmit audio, media, video, and remote desktop sessions. That removes the forms of communication most common on TeamTalk servers.

Consider this, as well. A person in this channel prevented from leaving via a password, could still cause problems. It won't prevent them from sending private messages to others, whether or not they're in the same channel. They could still be rude and abusive, or perhaps do some of the other things that caused them to be placed there in the first place. Now that I'm considering this more, there are so many ways around it, even if they have to remain within the channel, that it makes such a feature virtually useless. If there's ever a really good reason why such a feature should be used, other than banning isn't something someone likes to do much, I may consider it again, but there really isn't much point in such a feature when it's so easily circumvented in other ways.

These are my last thoughts on this issue, I think it should be closed.

**Comment by ntcarver0** [comment]
As others have said, this new "feature" could be easily abused by others, particularly on servers where administration is lax. For example, one possibility is that someone could set a leave password, then begin spamming audio or messages in that channel. Because people tend to leave those channels rather than  disconnecting altogether, these users would have a harder time getting out of this sort of situation unless they're the type to disconnect rather than leave channels.

**Comment by Ramon-Salazar** [comment]
@tech10 Leaving password and joining password are sepret things, simply only admins know that, also that isn't true that their freedom will be taken though they can simply send a privat message to one of the available admins, also for sometimes banning user for me isn't a good idea, for example if someone I don't know him/her well I can't contact him/her after banning him/her, so this is why I don't like the banning feature that much, and actually banning takes the freedom of joining the  server.

**Comment by tech10** [comment]
@Ramon-Salazar What do you do if the user is abusive after they are trapped in this channel because they haven't the password to leave it? If they send private messages to anyone they can in a manner that is harmful, what would you do then, especially if you didn't know them well? Should there then be a password to send private messages, or some sort of restriction to only allow them to send a private message to one specific user? If you stop banning a user for one reason and try to create some sort of other features to prevent them from leaving a channel, etc, then you have to create more features to close other avenues of potential abuse. This complicates things, simple is best. For example, if you ban someone you don't know well, and it's the only way you can contact that person, put a time limit on the ban and remove it yourself within a specific amount of time. Placing them in a channel they can't leave simply opens the door for them to be abusive or cruel in other ways, such as the private messages issue.

**Comment by Ramon-Salazar** [comment]
@tech10 still People can unsubscribe to privat messages if they want if they got abused

So, as I said there is nothing wront with this feature
