### ISSUE TITLE
Dark theme for Android client

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#477]
Here Google describes how to enable Dark Theme:
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#java

Yet when I enable it and change the activity as follows:
```
    <activity
            android:name=".ServerEntryActivity"
            android:label="@string/title_activity_server_entry"
            android:theme="@style/AppTheme"
    >
    </activity>
```
Then the Activity.getActionBar() call return null and the program crashes.

@poretsky , @beqabeqa473 Do you have any idea how to set up themes?

**Comment by poretsky** [comment]
Maybe, this theme does not provide action bar at all.

**Comment by poretsky** [comment]
I've investigated the problem. Please, @bear101 inform me what themes
intended to be used in what activities.

**Comment by bear101** [comment]
I was thinking all activities should use dark theme. I only managed to make it work in activities that don't have an action bar. But pretty much all activities in TT use action bar.

**Comment by poretsky** [comment]
In general, themes derived from Theme.AppCompat should be applied to
AppCompatActivity. Thus, we should use it instead of Activity and access
action bar with getSupportActionBar() instead of getActionBar(). I
think, such transition is reasonable, especially keeping in mind future
migration to androidx if we are planning it.

I can do this refactoring without touching general interface look except
of applying AppTheme and submit pull request or push it into master
branch directly. What the way would be preferable?

**Comment by bear101** [comment]
Can you do a pull request? Then I can test a bit before pushing it.

**Comment by poretsky** [comment]
Ok. Will do when ready.

**Comment by poretsky** [comment]
I've done the work in #547 and I have several notes and questions about
it.

1) This issue mentions dark theme, but actually AppTheme is derived from
Theme.AppCompat.Light. Is it by intention? I leave it as is anyway.

2) I did not touch WebLoginActivity since it uses its own theme that is
not derived from Theme.AppCompat. It looks good, but, maybe, it should
be refactored as well? Just for consistency.

3) I think, PreferencesActivity can (and should) be greatly simplified,
because it has native mechanism to distinguish screen sizes and use
two-panel layout when it is appropriate. In this case narrow screen
shows only headers at the first place and opens a section by touching
corresponding header. But I like this scenario better than showing long
list of all settings on one screen.

**Comment by bear101** [comment]
/1) This issue mentions dark theme, but actually AppTheme is derived from//
//Theme.AppCompat.Light. Is it by intention? I leave it as is anyway./

No, it is not intentional. But how do you choose user's default in
Theme.AppCompat.?

/2) I did not touch WebLoginActivity since it uses its own theme that is//
//not derived from Theme.AppCompat. It looks good, but, maybe, it should//
//be refactored as well? Just for consistency.//
/

I think it should also use the new Theme.AppCompat for consistency.

/3) I think, PreferencesActivity can (and should) be greatly simplified,//
//because it has native mechanism to distinguish screen sizes and use//
//two-panel layout when it is appropriate. In this case narrow screen//
//shows only headers at the first place and opens a section by touching//
//corresponding header. But I like this scenario better than showing long//
//list of all settings on one screen./

I was trying to simplify Preferences the other day but found it was not
easy. I was trying to move "Sound Events", "Subscriptions" and "Text to
Speech" to underlying activities. That way the preferences list would be
much smaller.


Kind regards

Bjoern Damstedt Rasmussen
www.bearware.dk

**Comment by poretsky** [comment]
Bjørn> I think it should also use the new Theme.AppCompat for
    Bjørn> consistency.

Suggested in #549.

    Bjørn> I was trying to simplify Preferences the other day but found
    Bjørn> it was not easy. I was trying to move "Sound Events",
    Bjørn> "Subscriptions" and "Text to Speech" to underlying
    Bjørn> activities. That way the preferences list would be much
    Bjørn> smaller.

Suggested in #550.

All three pull requests I've just submitted (#548, #549, #550) are
pretty independent.

**Comment by bear101** [comment]
I've merged all of them. Looks much better now. There were way too many options in preferences.

**Comment by bear101** [comment]
@poretsky I've changed AppTheme to point to Theme.AppCompat.DayNight. This seems to enable user's selected mode.

**Comment by poretsky** [comment]
Ok. I think, this issue may be closed.
