### ISSUE TITLE
migrate to androidX

### ISSUE THREAD

**Issue by beqabeqa473** [BearWare/TeamTalk5#579]
hi.

as google stopped developing support libraries, i think we should migrate to androidX.

i've created a branch with migration.

during tests, everything seems to work normaly.

**Comment by poretsky** [comment]
I've given a glance. It seems to be ok in general. Maybe, theming and
message sending functionality should be additionally tested due to
androidx migration. @bear101 Please, update Android beta since the last
one perhaps lacks latest changes, especially concerning back button
behaviour. And if everything is ok, I think, there are just enough
sensible changes in Android client to release it finally.
