### ISSUE TITLE
Ability to specify gender on mobile clients

### ISSUE THREAD

**Issue by Oreonan** [BearWare/TeamTalk5#656]
Currently, we can only specify gender on QT and classic client. It can be good to have the ability to personalize this on all lients, including Android and IOS clients.

**Comment by bear101** [comment]
@poretsky, @beqabeqa473  Would it be an idea to switch to emojis instead of images? I'm also thinking for volume control in the Android client. Currently it's buttons with images.

**Comment by beqabeqa473** [comment]
why not? not all but most tts engines can read emojis, so i think i can be a way to go, however it would be goot to know what @poretsky think about that.

**Comment by poretsky** [comment]
Android client accessibility would not be affected since it relies on
contentDescription field. But I don't understand what the advantage we
hope to get of this change.

**Comment by ChrisDuffley** [comment]
Yes, but don't we want gender as part of the information being displayed especially since it may be displayed onscreen already?

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On Sep 20, 2020, at 16:36, Igor B. Poretsky <notifications@github.com> wrote:


Android client accessibility would not be affected since it relies on
contentDescription field. But I don't understand what the advantage we
hope to get of this change.

**Comment by DalisonCPU** [comment]
I think there must be a way to detect that the screen reader is running to show the genre or not.
-----Mensagem original-----
De: ChrisDuffley <notifications@github.com>
Para: BearWare/TeamTalk5 <TeamTalk5@noreply.github.com>
Data: Domingo, 20 de Setembro de 2020 14:39
Assunto: Re: [BearWare/TeamTalk5] Ability to specify gender on mobile clients(#656)

Yes, but don't we want gender as part of the information being displayed especially since it may be displayed onscreen already?



Christopher Duffley



Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>



LINKS TO SUBSCRIBE:



iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>



LIKE/FOLLOW Me:



Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>



On Sep 20, 2020, at 16:36, Igor B. Poretsky <notifications@github.com> wrote:





Android client accessibility would not be affected since it relies on

contentDescription field. But I don't understand what the advantage we

hope to get of this change.

â
