### ISSUE TITLE
TT5Classic becomes VERY slow with more than 25 users

### ISSUE THREAD

**Issue by wandogau** [BearWare/TeamTalk5#673]
Hello together,
If there are more than 25 or 30 users on our server, TT5Classic becomes very slow. Not the transmission, but the program itself.
If you open TT5Classic you can hear people talking in the root channel but until you cann see, or navigate, the channel tree, it takes more than 10, sometimes 30 seconds. If TT5Classic is open, you can navigate the channel tree, but until you get an answer from the screenreader, it takes between 5 and ten seconds. 
This we have found on several pcs with different internet connections.
All testers use a screenreader, NVDA and/or JAWS.
I guess the problem is, that the channel view is updated very often, which is great, but the screenreader always tries to update it and this freezes the machine.
I have two suggestions to solve this, because it is very important for us to get this solved:
You can use just a listview instead of a treeview, just like in windows explorer. With such lists all screenreader-users are very familiar. So, to go into a room press enter on it, and the list shows only the users and channels in this room, to go back just hit backspace.
Suggestion 2, maybe it's possible to update just the selected item instead of repainting the whole tree, because a screenreader user only can see one item at a time.
If you need more information on this, just let me know!
A solution is very appreciated!
Best regards
Wandogau

**Comment by bear101** [comment]
Duplicate: #573

**Comment by beqabeqa473** [comment]
it is due to custom sorting.

that is one of causes i could identify.

i tried to turn off custom tree sorting, but in this case, channels
and users are beeing shuffled.
i wasn't epxrimenting more in this area so i don't know how to fix it yet.

On 12/31/20, Bjørn Damstedt Rasmussen <notifications@github.com> wrote:
> Duplicate: #573
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/673#issuecomment-752859088


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
Follow duplicate issue to get latest update
