### ISSUE TITLE
Remove Facebook Login

### ISSUE THREAD

**Issue by tigexplorer** [BearWare/TeamTalk5#682]
Hi,

Exodus lists several Facebook Trackers for the Android App:

[https://reports.exodus-privacy.eu.org/en/reports/154099/](https://reports.exodus-privacy.eu.org/en/reports/154099/)

No one of these are listed in the PlayStore or in the TeamTalk Privacy Policy on 

[http://www.bearware.dk/teamtalk/ttprivacy.txt](http://www.bearware.dk/teamtalk/ttprivacy.txt)

Is it possible to use TeamTalk for Android without this, e.g. via F-Droid?
Or better, is it possible to remove this from the App?

**Comment by bear101** [comment]
I'm actually thinking of removing Facebook login because it's a pain to maintain. Facebook constantly change their policies and force developers to update their apps.

It's a bit hard to know how many people are using Facebook login therefore I'm a bit reluctant to remove it.

Facebook tracking is only active if you use Facebook login in TeamTalk.

**Comment by bear101** [comment]
Another issue with Facebook is that Facebook depend on Webkit which prevents TeamTalk from being added to Apple's App Store.
