### ISSUE TITLE
Event sounds should not cue

### ISSUE THREAD

**Issue by burakyuksek** [BearWare/TeamTalk5#694]
Let's say we're using some long sounds for events. Login sound is 1 second long, logout sound is half a second long. When 3 users enter and leave at once, the enter and leave sounds just play over and over.
Instead they should just play without waiting for the previous one to finish.

**Comment by Oreonan** [comment]
I'm totally agree with this idea. In addition it is already the case on 
QT client. I've searched a solution for this problem but found nothing. 
@bear101 have you an idea?

**Comment by bear101** [comment]
Try changing PlayWaveFile() to "TRUE" for Async: https://github.com/BearWare/TeamTalk5/blob/master/Client/TeamTalkClassic/PlaySoundThread.cpp#L111

If I remember correctly this will, however, make short files skip playback.

**Comment by Oreonan** [comment]
Thanks, this is the solution.

I do not see this when I make some tests with short files, all sounds 
works correctly, I'll make the modification on the repo

**Comment by beqabeqa473** [comment]
discovered an issue.

when turning on/off voice activation with control+shift+a for example, releasing ptt interrupts playing sound of voice activation.

**Comment by beqabeqa473** [comment]
very problematic thing.

sounds are interrupting and it is possible to miss some events.

this change should be reverted or change should be done only for specific sounds, however what we call specific sounds is a question.

ideally, they should not interrupted, but multiple sounds should be played at the same time.
but for now, this change makes big problems.

**Comment by Oreonan** [comment]
I've reverted b0ce209
If we find better solution, we will make a new commit.

**Comment by bear101** [comment]
When files names are submitted to PlaySoundThread they could maybe
include a "priority" variable, so certain files are ensured to be
played. E.g.

struct SoundFile
{
    CString szFilename;
    BOOL bSyncPlayback;
};


Kind regards

Bjørn Damstedt Rasmussen
www.bearware.dk

**Comment by burakyuksek** [comment]
Hello,
I think simply sounds should play over each other. They shouldn't interrupt each other either.

**Comment by Oreonan** [comment]
There is a solution to do this @bear101

**Comment by bear101** [comment]
@Oreonan in commit 613740b822785ba6640cec2deef57fcfe64ae884 I've changed sound events to be played by TeamTalk's sound system.

You can change playback between these modes: https://github.com/BearWare/TeamTalk5/blob/master/Client/TeamTalkClassic/PlaySoundThread.h#L29

When using PLAYBACKMODE_TEAMTALK (the default now) you can change volume of audio files here:
https://github.com/BearWare/TeamTalk5/blob/master/Client/TeamTalkClassic/PlaySoundThread.cpp#L130

Choose PLAYBACKMODE_SYNC to switch back to previous behavior.

**Comment by Oreonan** [comment]
I'll test this. Can you also change playsoundevent function to be a 
global function? Some users has required me to add an option to play 
sounds when sending public or private messages but it's require 
playsoundevent to be call on messagedlg.cpp

**Comment by bear101** [comment]
@Oreonan 
With commit 75a3df4 you have access to CTeamTalkDlg instance and can do like this from CMessageDlg:
`    m_pParent->PlaySoundEvent()`

**Comment by beqabeqa473** [comment]
Hello all.

after testing latest classic version of teamtalk, lots of users started complaining about loudness of sounds.

while i like a new behaviour, because it is possible to switch sound devices and sounds are switching too, some part of users are using a pair of headphones, where overal system volume is very high, so they are turning down master volume and are increasing apps which they need.
again, while i am against to increase tt volume to 100%, some of users are doing this. so, because of setting maximum volume, sounds are distorted.

it would be good to implement one of the following:
make configurable slider in preferences to set volume of sounds
or make it possible to select in preferences between new and old behaviour.

i don't think reverting this would be a good idea, because this approach has more benefits.

**Comment by beqabeqa473** [comment]
@bear101 @Oreonan what do you think about it?

**Comment by Oreonan** [comment]
I'm agree to add an option to choose bitween new and old behavior

**Comment by bear101** [comment]
Currently we have a voice vs. media file volume. I guess we should have the same for sound events.

**Comment by beqabeqa473** [comment]
yes, that would be a good thing.

because as i said, lots of people for some reason are using tt at 100%
of master volume, and in this case, sounds are very loud.

On 2/7/21, Bjørn Damstedt Rasmussen <notifications@github.com> wrote:
> Currently we have a voice vs. media file volume. I guess we should have the
> same for sound events.
>
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/694#issuecomment-774725536


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Oreonan** [comment]
In fact, I think two options can be good. One for choose behavior of 
sound playing, and another to choose sounds volume.

So maybe we must have to add this 2 new options?
