### ISSUE TITLE
TeamTalk 5 Classic Freezing on Connection to Server

### ISSUE THREAD

**Issue by njsch** [BearWare/TeamTalk5#700]
There appears to be an issue in the classic installation of the client where the program sometimes freezes upon connection.  I am not sure what causes but it has occurred when using both the JAWS and NVDA assistive (screen-reading) technologies.  The client successfully connects to the server but does not respond to keyboard input.

I am wondering if I may have accedintally modified an interface setting somewhere because the client started working again after I reinstalled it.  So just putting this here for reference.  I'm afraid I cannot provide any extra specific steps for reproducing this issue.

**Comment by ChrisDuffley** [comment]
If I may ask, how long is this client freeze occurring? If it's only a few seconds, I have no idea why it does it, but on certain domains/servers it can freeze although on others it does not.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On Jan 3, 2021, at 19:26, Nathaniel Schmidt <notifications@github.com> wrote:


There appears to be an issue in the classic installation of the client where the program sometimes freezes upon connection. I am not sure what causes but it has occurred when using both the JAWS and NVDA assistive (screen-reading) technologies. The client successfully connects to the server but does not respond to keyboard input.

I am wondering if I may have accedintally modified an interface setting somewhere because the client started working again after I reinstalled it. So just putting this here for reference. I'm afraid I cannot provide any extra specific steps for reproducing this issue.

**Comment by njsch** [comment]
The freeze occurs indefinitely on a tthub.org server, udb and tcp ports both 10050.  I’ve probably tested it for max. 30secs.

**Comment by zstanecic** [comment]
The freeze occurs in all 5x versions, and especially if you have a server with large channel list. This freeze is not occuring in the qt client. The freeze also occurs if you try to join the channel on such a large server.

**Comment by bear101** [comment]
Duplicate #573

**Comment by bear101** [comment]
Follow duplicate issue to get latest update
