### ISSUE TITLE
TeamTalk5 clasic 5.7 beta still lag

### ISSUE THREAD

**Issue by rexya2017** [BearWare/TeamTalk5#731]
Hi, yesterday I was invited to my friend's server, and there are lots of users there, I think there are about 150 active users, and there are approximately 30 to 40 channels available.
The problem that occurred in TeamTalk5 clasic 5.7 beta, when I entered the server it was still lagging, and the client was potentially not responding.
So I think the change log "-Faster login on servers with many users or channels" isn't really working yet. but if there are only 50 active users on the server, it doesn't matter.

**Comment by beqabeqa473** [comment]
Faster login works great.

it is caused by another issue.

On 1/17/21, rexya2017 <notifications@github.com> wrote:
> Hi, yesterday I was invited to my friend's server, and there are lots of
> users there, I think there are about 150 active users, and there are
> approximately 30 to 40 channels available.
> The problem that occurred in TeamTalk5 clasic 5.7 beta, when I entered the
> server it was still lagging, and the client was potentially not responding.
> So I think the change log "-Faster login on servers with many users or
> channels" isn't really working yet. but if there are only 50 active users on
> the server, it doesn't matter.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/731


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by bear101** [comment]
If you disable TTS and/or sound events does this improve performance?

**Comment by bear101** [comment]
Cannot reproduce
