### ISSUE TITLE
better accessibility of Linux client with Orca screenreader

### ISSUE THREAD

**Issue by werwoelfchen** [BearWare/TeamTalk5#738]
For better accessibility of the linux client it is necessary to have a short key for opening the menu bar of TT. In the preferences window, aspecially in the sound page there are all check boxes without any describtion.

**Comment by beqabeqa473** [comment]
hello.

as for checkboxes it is not a teamtalk bug, it was bug in orca's qt
implementation, which was fixed in march or april of previous year.
so, you need to update orca.

On 1/24/21, werwoelfchen <notifications@github.com> wrote:
> For better accessibility of the linux client it is necessary to have a short
> key for opening the menu bar of TT. In the preferences window, aspecially in
> the sound page there are all check boxes without any describtion.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/BearWare/TeamTalk5/issues/738


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by Oreonan** [comment]
And, for open menu bar, you must have to use alt key in all QT applications on Linux.
