### ISSUE TITLE
It is recommended that you can choose to make your server available to the public in a better way.

### ISSUE THREAD

**Issue by olsen-zhang** [BearWare/TeamTalk5#797]
In the past, to introduce our friends to log in to our server, we had to ask the administrator to assist in helping them register their user accounts, which added a lot of unnecessary hassle for the administrator.
  Now, we can choose a more convenient independent management system, we can choose to open a visitor account, friends can register their ordinary user accounts through the visitor account, the registration behavior can be directly bound to the MAC address or machine code has been to prevent abuse.
  Also, it is recommended to add a feature to turn off voice activation for all people, instead of just disabling voice transmission for all people.Then you can set an alert sound to mute all and unmute all.
Finally, I would like to thank the authors for their hard work and wish this software a perfect future.

**Comment by xyzs0000** [comment]
I very much support the above statement###

**Comment by bear101** [comment]
BearWare.dk WebLogin has been created so administrators don't have to create and update user accounts. This also means that administrators don't know the user's password, so the identity of a user is more secure.

Spammers will also have a harder time to relogin after a ban since they have to create a new user account and bypass Wordpress' spam protection (BearWare.dk WebLogin uses Wordpress' spam protection).

**Comment by bear101** [comment]
Read more about TeamTalk 5 Pro Server here: https://bearware.dk/?page_id=976
