### ISSUE TITLE
First server in serverlistdlg.cpp is always shown

### ISSUE THREAD

**Issue by bear101** [BearWare/TeamTalk5#915]
After commit 9e2f114d6ff274bb7d7a6068660a1ca925768aef it is no longer the "latest server" that is shown. Instead it's always server index 0 in server listbox.

**Comment by bear101** [comment]
@Oreonan I'm still getting this issue. If I connect to public server "TeamTalk 5 Encrypted Server (UK)" then disconnect and press F2 again. Then the first server on the list is selected.

When serverlistdlg-class opens then it should display the previous server in the edit-fields and no server should be selected.

**Comment by Oreonan** [comment]
Ah OK, I not understood you want this :), I thought you only want to 
keep selection after addition or deletion. I'll look at to it.

**Comment by bear101** [comment]
No, if you enter a new server and don't save it then next time it should appear in the edit-fields

**Comment by ChrisDuffley** [comment]
Yes, this is what's supposed to happen, especially if all you're doing is restarting the application and then reconnecting. Yes, the Join Latest Server on Startup setting would work, but not always for my use case because I have a lot of servers on my INI file.

Christopher Duffley

Host of Mission Possible Podcast <http://www.missionpossiblepodcast.com/>

LINKS TO SUBSCRIBE:

iTunes <https://itunes.apple.com/us/podcast/mission-possible-christopher/id1103092109?mt=2> | Stitcher <http://www.stitcher.com/s?fid=88094&refid=stpr> | Google Play <https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ik76dexklcprwnpuxbdr2s6bm3y?t=Mission_Possible_with_Christopher_Duffley> | Follow Podcast On TuneIn And Listen To Latest Episode <http://tunein.com/radio/Mission-Possible-With-Christopher-Duffley-p892505/>

LIKE/FOLLOW Me:

Facebook <http://facebook.com/christopherduffley> | Twitter <http://twitter.com/chrisduffley> | YouTube <http://youtube.com/christopherduffley> | Instagram <http://instagram.com/christopherduffley>

On Jun 7, 2021, at 15:16, Bjørn Damstedt Rasmussen ***@***.***> wrote:


@Oreonan <https://github.com/Oreonan> I'm still getting this issue. If I connect to public server "TeamTalk 5 Encrypted Server (UK)" then disconnect and press F2 again. Then the first server on the list is selected.

When serverlistdlg-class opens then it should display the previous server in the edit-fields and no server should be selected.

**Comment by Oreonan** [comment]
Only way I see for now is to move focus to another place. QListWidget class has no way to select nothing I'm afraid.
