### ISSUE TITLE
separate nickname for each server in classic client.

### ISSUE THREAD

**Issue by amirmahdifard0** [BearWare/TeamTalk5#972]
As you know, in android client, we can click on the name of each server for a long time and from the information editing page of that server, write a separate nickname for that server that every time we enter that server, the same nickname is displayed. Unfortunately, this feature does not exist in the classic Windows client. Please add this feature to classic so that we can write a separate nickname for that server from the server information editing section, so that the same nickname is displayed every time we enter that server. Just like Android. I do not know qt client, but I need this feature in classic client.

**Comment by bear101** [comment]
@Oreonan Should we skip this feature in Classic client and say it's only available in Qt Client?

**Comment by Oreonan** [comment]
Yes, I think.

**Comment by amirmahdifard0** [comment]
But this is an important feature. And we really need it. Please accept it and do so.

**Comment by amirmahdifard0** [comment]
I don't understand why you're using this? You're saying that implementing this feature is really hard. But in the end what? Is Teamtalk development harder than disassembling a feature? That is, you will not do such a thing at all? I'm not asking you anything unnecessary. Most blind people use classic and this feature is very important for them. Please add this feature.

**Comment by jeremyp3** [comment]
if most blind people need this feature, they will use client qt. I'm
blind, and I'm using the client qt, and I'm not having any major
accessibility issues

**Comment by amirmahdifard0** [comment]
But what if those who have updated to classic and want to use this feature in classic? Your reason is not convincing. They have no problem adding this feature. Just say hard.

**Comment by Oreonan** [comment]
Hi,
we are aware that the transition from classic to Qt isn't really easy to understand, because classic has been here from long time. Every framework have some specificities and for us it's not really easy to make available all features in 2 clients in the same time. Recently we have decided to encourage users to switch to the Qt client, and we are hard working on accessibility improvements to make this transition more easy.
Qt has some minor accessibility issues, but Windows isn't the OS more affect by this problems. In other platforms, Qt client has always been the only available client, and for some platforms Qt has major issues, I think aspecially to MacOS when I write this.
If we have decided to encourage users to switch from classic to Qt, it's because we don't have an expansive time, and make all features available in 2 clients request a lot of time. More, the GUI framework used in classic is a quite out dated.
For now, classic is, in my opinion, in an extanded support phase, basically if a several issue is find, we'll probably fix it, and if internal changes to TT require change to make classic still working, we'll probably make this changes also.
Personally I switched from classic to Qt some months ago, and now I use only the Qt, I did it to work on accessibility of this client, but also to see if use this client all days on Windows is possible for a blind user, and the answer is yes.
I reported some accessibility issues directly to Qt because we can't fix all issues, now Qt team is working on fixes for this issues.
One day, when Qt will be ready with accessibility fixes and when we'll can build TT with a better Qt accessibility, classic will probably be totally stop developing.
I hope your understand this explications, I know that change habits it's not easy for all, but unfortunately we can't satisfact all users.
Thanks for your comprehension.
